services:
  db_test:
    image: postgres:14
    environment:
      POSTGRES_DB: easycamper_test
      POSTGRES_USER: easycamper
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

  server_test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_test
    environment:
      - NODE_ENV=test
      - DB_HOST=db_test
      - DB_USER=easycamper
      - DB_PASSWORD=secret123
      - DB_NAME=easycamper_test
      - DB_PORT=5432
    command: ["npm", "test"]

volumes:
  db_test_data: