version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: easycamper
      POSTGRES_USER: easycamper
      POSTGRES_PASSWORD: secret123
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
