name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: easycamper
          POSTGRES_PASSWORD: secret123
          POSTGRES_DB: easycamper_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: server
        run: npm ci

      - name: Wait for Postgres
        run: npx wait-on tcp:localhost:5432

      - name: Run migrations
        working-directory: server
        run: npx sequelize-cli db:migrate --env test

      - name: Seed test data
        working-directory: server
        run: npx sequelize-cli db:seed:all --env test

      - name: Run tests
        working-directory: server
        run: npm test
